name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.13.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.13.0
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
